// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDTn-ycVJLEF78a4oDJu5dbj6YRkqSMg',
    appId: '1:579499922173:web:8ffe629b206ea9f1656494',
    messagingSenderId: '579499922173',
    projectId: 'stressmate-net',
    authDomain: 'stressmate-net.firebaseapp.com',
    storageBucket: 'stressmate-net.firebasestorage.app',
    measurementId: 'G-T9NDWSJ6C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMYH9yXVujJozVciQos5TRHbOVGwFrps',
    appId: '1:579499922173:android:4e959c9a1156f9ab656494',
    messagingSenderId: '579499922173',
    projectId: 'stressmate-net',
    storageBucket: 'stressmate-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGOKZp4D0zTBqaEokWN-rKLYUffLxx4c',
    appId: '1:579499922173:ios:df6700b3898eb943656494',
    messagingSenderId: '579499922173',
    projectId: 'stressmate-net',
    storageBucket: 'stressmate-net.firebasestorage.app',
    iosClientId: '579499922173-5dlf98k8avs01u140jamg4k0kls9noo0.apps.googleusercontent.com',
    iosBundleId: 'stress.mate.com.stressmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjGOKZp4D0zTBqaEokWN-rKLYUffLxx4c',
    appId: '1:579499922173:ios:df6700b3898eb943656494',
    messagingSenderId: '579499922173',
    projectId: 'stressmate-net',
    storageBucket: 'stressmate-net.appspot.com',
    iosBundleId: 'stress.mate.com.stressmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoDTn-ycVJLEF78a4oDJu5dbj6YRkqSMg',
    appId: '1:579499922173:web:88a4dfe96d9a04a6656494',
    messagingSenderId: '579499922173',
    projectId: 'stressmate-net',
    authDomain: 'stressmate-net.firebaseapp.com',
    storageBucket: 'stressmate-net.appspot.com',
    measurementId: 'G-7XXZ8C6DPV',
  );
}